version: '2.2'

services:
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=chat_service
    expose:
    - "3306"
    ports:
    - "33060:3306"

  chat-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: chat-service
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/chat_service
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=password
    - JAVA_OPTS=-Xms128M -Xmx256M -XX:MaxMetaspaceSize=128M
    depends_on:
    - mysql
    links:
    - mysql
    expose:
    - "8080"
    ports:
    - "8080:8080"
    mem_limit: 512M
