apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - name: mysql-port
    port: 3306
    nodePort: 30001

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: mysql

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 400m
            memory: 1024Mi
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-schema
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-claim

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
data:
  db-username: cm9vdA==
  db-password: cGFzc3dvcmQ=
  db-schema: cmVzZXJ2YXRpb25zX3NlcnZpY2U=
