server:
  port: 8080
  use-forward-headers: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_service?createDatabaseIfNotExist=true
    username: root
    password: password
    max-active: 20
    max-idle: 20
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000
  flyway:
    enabled: true
    clean-disabled: true
    clean-on-validation-error: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

signature:
  validation:
    use:
      https: false

encryption:
  key: 9MDJZy0kgctfIuBP
  initVector: DmSiQBV2HFibxReH

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,loggers,metrics
      path-mapping:
        loggers: api/v1/admin/loggers

logging:
  level:
    ROOT: INFO

message:
  content:
    typeKey: type
    text:
      textKey: text
    image:
      urlKey: url
      heightKey: height
      widthKey: width
    video:
      urlKey: url
      sourceKey: source
